version: '3.8'

services:
  backend:
    image: docker.io/library/crane_test
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app/
    command: /app/venv/bin/python3 crane_control/crane_control.py
    ports:
      - "8765:8765"
    network_mode: host
    ipc: host

  http-server:
    image: docker.io/library/crane_test
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app/config
    command: http-server -c-1
    ports:
      - "8080:8080"
    network_mode: host
    ipc: host

  proxy-server:
    image: docker.io/library/crane_test
    command: node /app/proxy-server/server.js
    ports:
      - "3000:3000"
    depends_on:
      - http-server
    network_mode: host
    ipc: host